// Date: 2016/6/24 23:00:12
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelNew extends ModelBase
{
  //fields
    ModelRenderer Head;
    ModelRenderer Body;
    ModelRenderer Tail;
    ModelRenderer Leg1;
    ModelRenderer Leg2;
    ModelRenderer Leg3;
    ModelRenderer Leg4;
    ModelRenderer Ear1;
    ModelRenderer Ear2;
  
  public ModelNew()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Head = new ModelRenderer(this, 0, 0);
      Head.addBox(-4F, -4F, -8F, 8, 8, 8);
      Head.setRotationPoint(0F, 15F, -4F);
      Head.setTextureSize(64, 32);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      Body = new ModelRenderer(this, 32, 0);
      Body.addBox(-3F, -3F, 0F, 6, 6, 10);
      Body.setRotationPoint(0F, 15F, -4F);
      Body.setTextureSize(64, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Tail = new ModelRenderer(this, 0, 18);
      Tail.addBox(-1F, -1F, 0F, 2, 2, 8);
      Tail.setRotationPoint(0F, 15F, 6F);
      Tail.setTextureSize(64, 32);
      Tail.mirror = true;
      setRotation(Tail, -0.0698132F, 0F, 0F);
      Leg1 = new ModelRenderer(this, 22, 19);
      Leg1.addBox(-1F, 0F, -1F, 2, 6, 2);
      Leg1.setRotationPoint(2F, 18F, 3F);
      Leg1.setTextureSize(64, 32);
      Leg1.mirror = true;
      setRotation(Leg1, 0F, 0F, 0F);
      Leg2 = new ModelRenderer(this, 22, 19);
      Leg2.addBox(-1F, 0F, -1F, 2, 6, 2);
      Leg2.setRotationPoint(-2F, 18F, 3F);
      Leg2.setTextureSize(64, 32);
      Leg2.mirror = true;
      setRotation(Leg2, 0F, 0F, 0F);
      Leg3 = new ModelRenderer(this, 22, 19);
      Leg3.addBox(-1F, 0F, -1F, 2, 6, 2);
      Leg3.setRotationPoint(-2F, 18F, -2F);
      Leg3.setTextureSize(64, 32);
      Leg3.mirror = true;
      setRotation(Leg3, 0F, 0F, 0F);
      Leg4 = new ModelRenderer(this, 22, 19);
      Leg4.addBox(-1F, 0F, -1F, 2, 6, 2);
      Leg4.setRotationPoint(2F, 18F, -2F);
      Leg4.setTextureSize(64, 32);
      Leg4.mirror = true;
      setRotation(Leg4, 0F, 0F, 0F);
      Ear1 = new ModelRenderer(this, 32, 20);
      Ear1.addBox(0F, -5F, 0F, 5, 5, 1);
      Ear1.setRotationPoint(2F, 13F, -10F);
      Ear1.setTextureSize(64, 32);
      Ear1.mirror = true;
      setRotation(Ear1, 0F, 0F, 0F);
      Ear2 = new ModelRenderer(this, 32, 20);
      Ear2.addBox(-5F, -5F, 0F, 5, 5, 1);
      Ear2.setRotationPoint(-2F, 13F, -10F);
      Ear2.setTextureSize(64, 32);
      Ear2.mirror = true;
      setRotation(Ear2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Head.render(f5);
    Body.render(f5);
    Tail.render(f5);
    Leg1.render(f5);
    Leg2.render(f5);
    Leg3.render(f5);
    Leg4.render(f5);
    Ear1.render(f5);
    Ear2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
