// Date: 2016/6/24 23:00:12
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package WdawningStudio.DawnW.science.entity;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

@SideOnly(Side.CLIENT)
public class ModelMouse extends ModelBase
{
  //fields
    private ModelRenderer Head;
    private ModelRenderer Body;
    private ModelRenderer Tail;
    private ModelRenderer Leg1;
    private ModelRenderer Leg2;
    private ModelRenderer Leg3;
    private ModelRenderer Leg4;
    private ModelRenderer Ear1;
    private ModelRenderer Ear2;
    
    public ModelMouse()
    {  	
    	this.Head = new ModelRenderer(this, 0, 0);
    	this.Head.addBox(-4F, -4F, -8F, 8, 8, 8);
    	this.Head.setRotationPoint(0F, 15F, -4F);
    	this.Body = new ModelRenderer(this, 32, 0);
    	//this.Body.addBox(-3F, -3F, 0F, 6, 6, 10);
    	//this.Body.setRotationPoint(0F, 15F, -4F);
    	this.Body.addBox(-3F, 0F, -3F, 6, 10, 6);
    	this.Body.setRotationPoint(0F, 15F, -4F);
    	this.Tail = new ModelRenderer(this, 0, 18);
    	this.Tail.addBox(-1F, -1F, 0F, 2, 2, 8);
    	this.Tail.setRotationPoint(0F, 15F, 6F);
    	this.Leg1 = new ModelRenderer(this, 22, 19);
    	this.Leg1.addBox(-1F, 0F, -1F, 2, 6, 2);
    	this.Leg1.setRotationPoint(2F, 18F, 3F);
    	this.Leg2 = new ModelRenderer(this, 22, 19);
    	this.Leg2.addBox(-1F, 0F, -1F, 2, 6, 2);
    	this.Leg2.setRotationPoint(-2F, 18F, 3F);
    	this.Leg3 = new ModelRenderer(this, 22, 19);
    	this.Leg3.addBox(-1F, 0F, -1F, 2, 6, 2);
    	this.Leg3.setRotationPoint(-2F, 18F, -2F);
    	this.Leg4 = new ModelRenderer(this, 22, 19);
    	this.Leg4.addBox(-1F, 0F, -1F, 2, 6, 2);
    	this.Leg4.setRotationPoint(2F, 18F, -2F);
    	this.Ear1 = new ModelRenderer(this, 32, 20);
    	this.Ear1.addBox(0F, -5F, 0F, 5, 5, 1);
    	this.Ear1.setRotationPoint(2F, 13F, -10F);
    	this.Ear2 = new ModelRenderer(this, 32, 20);
    	this.Ear2.addBox(-5F, -5F, 0F, 5, 5, 1);
    	this.Ear2.setRotationPoint(-2F, 13F, -10F);
    }
    
    @Override
    public void render(Entity entity, float limbSwing, float limbSwingAmount, float rotateFloat, float rotateYaw,
            float rotatePitch, float scale)
    {
        this.setRotationAngles(limbSwing, limbSwingAmount, rotateFloat, rotateYaw, rotatePitch, scale, entity);
        this.Head.render(scale);
        this.Body.render(scale);
        this.Tail.render(scale);
        this.Leg1.render(scale);
        this.Leg2.render(scale);
        this.Leg3.render(scale);
        this.Leg4.render(scale);
        this.Ear1.render(scale);
        this.Ear2.render(scale);
    }
  
    @Override
    public void setRotationAngles(float limbSwing, float limbSwingAmount, float rotateFloat, float rotateYaw,
            float rotatePitch, float scale, Entity entity)
    {
        this.Head.rotateAngleX = rotatePitch / (180F / (float)Math.PI);
        this.Head.rotateAngleY = rotateYaw / (180F / (float)Math.PI);
        this.Body.rotateAngleX = ((float)Math.PI / 2F);
        this.Leg1.rotateAngleX = MathHelper.cos(limbSwing * 0.6662F) * 1.4F * limbSwingAmount;
        this.Leg2.rotateAngleX = MathHelper.cos(limbSwing * 0.6662F + (float)Math.PI) * 1.4F * limbSwingAmount;
        this.Leg3.rotateAngleX = MathHelper.cos(limbSwing * 0.6662F + (float)Math.PI) * 1.4F * limbSwingAmount;
        this.Leg4.rotateAngleX = MathHelper.cos(limbSwing * 0.6662F) * 1.4F * limbSwingAmount;
    }

}
